provider:
  environment:
    ${name}: ${service}-${stage}-${name}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:provider.environment.${name}}/*"

functions:
  ${name}-python:
    handler: resource/python-executer/handler.handler
    runtime: python3.7
    events:
      - http:
          path: /py
          method: post
          cors: true

resources:
  Resources:
    ${name}:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${service}-${stage}-${name}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: [GET, PUT]
              AllowedOrigins: ["*"]
              Id: CORSRuleId1
              MaxAge: "3600"
        VersioningConfiguration:
          Status: Enabled
